import 'package:flutter/material.dart';

class AppLanguage { final String code; final String name; final String nativeName; const AppLanguage(this.code,this.name,this.nativeName); }
class AppLanguages { static const supported=<AppLanguage>[AppLanguage('en','English','English'),AppLanguage('hi','Hindi','हिन्दी'),AppLanguage('mr','Marathi','मराठी')]; }
class AppLocale { static String code='en'; static final ValueNotifier<String> notifier=ValueNotifier(code); static void set(String value){code=value;notifier.value=value;} static AppLanguage get current=>AppLanguages.supported.firstWhere((l)=>l.code==code,orElse:()=>AppLanguages.supported.first); }
class L10n { static String t(String key)=>_strings[AppLocale.code]?[key]??key; static const _strings=<String,Map<String,String>>{
  'hi': {
      'Welcome back': 'वापसी पर स्वागत है',
      'Sign in': 'साइन इन',
      'Username': 'उपयोगकर्ता नाम',
      'Password': 'पासवर्ड',
      'Language': 'भाषा',
      'Your craft. Your story. Your marketplace.': 'आपका हुनर। आपकी कहानी। आपका बाज़ार।',
      'Sign in to your artisan workspace.': 'अपने कारीगर कार्यक्षेत्र में साइन इन करें।',
      'DEMO ACCESS': 'डेमो एक्सेस',
      'Prototype account only. Replace demo authentication before real deployment.': 'केवल प्रोटोटाइप खाता। वास्तविक उपयोग से पहले डेमो प्रमाणीकरण बदलें।',
      'Made for the people behind the craft ✦': 'हुनर के पीछे के लोगों के लिए बनाया गया ✦',
      'Dashboard': 'डैशबोर्ड',
      'Analytics': 'विश्लेषण',
      'Products': 'उत्पाद',
      'Orders': 'ऑर्डर',
      'Marketplace': 'बाज़ार',
      'Settings': 'सेटिंग्स',
      'Home': 'होम',
      'Markets': 'बाज़ार',
      'Your craft is going places.': 'आपका हुनर आगे बढ़ रहा है।',
      'Here’s what’s happening in your artisan business.': 'आपके कारीगर व्यवसाय में अभी क्या हो रहा है।',
      'View analytics': 'विश्लेषण देखें',
      'View page': 'पेज देखें',
      'Create a product': 'उत्पाद बनाएँ',
      'Create product listing': 'उत्पाद सूची बनाएँ',
      'Save product': 'उत्पाद सहेजें',
      'Save profile': 'प्रोफ़ाइल सहेजें',
      'Log out': 'लॉग आउट',
      'Groq API key': 'Groq API कुंजी',
      'Apply API keys': 'API कुंजी लागू करें',
      'AI configuration': 'AI कॉन्फ़िगरेशन',
      'Artisan profile': 'कारीगर प्रोफ़ाइल',
      'Your name': 'आपका नाम',
      'Business / craft name': 'व्यवसाय / शिल्प का नाम',
      'Contact number': 'संपर्क नंबर',
      'Location': 'स्थान',
      'About your craft / business': 'आपके शिल्प / व्यवसाय के बारे में',
      'Profile saved for this session.': 'प्रोफ़ाइल इस सत्र के लिए सहेजी गई।',
      'AI keys set in memory for this session.': 'AI कुंजियाँ इस सत्र के लिए मेमोरी में सेट हैं।',
      'Take photo': 'फोटो लें',
      'Upload photos': 'फोटो अपलोड करें',
      'Craft details': 'शिल्प विवरण',
      'Product name (optional)': 'उत्पाद का नाम (वैकल्पिक)',
      'Category': 'श्रेणी',
      'Tell us about the product': 'उत्पाद के बारे में बताएँ',
      'What is it? How is it made? What makes it special?': 'यह क्या है? इसे कैसे बनाया जाता है? इसे खास क्या बनाता है?',
      'Materials (if known)': 'सामग्री (यदि ज्ञात हो)',
      'Price & production': 'कीमत और उत्पादन',
      'Your selling price (₹)': 'आपकी बिक्री कीमत (₹)',
      'Units you can make': 'आप कितनी इकाइयाँ बना सकते हैं',
      'In how many days?': 'कितने दिनों में?',
      'AI listing studio': 'AI लिस्टिंग स्टूडियो',
      'Generate buyer-ready listing': 'खरीदार के लिए लिस्टिंग बनाएँ',
      'Generating…': 'बनाया जा रहा है…',
      'Cancel': 'रद्द करें',
      'Close': 'बंद करें',
      'Preview listing': 'लिस्टिंग देखें',
      'Publish (demo)': 'प्रकाशित करें (डेमो)',
      'Demo publish': 'डेमो प्रकाशन',
      'Connect demo': 'डेमो कनेक्ट करें',
      'Share listing': 'लिस्टिंग साझा करें',
      'Share product page': 'उत्पाद पेज साझा करें',
      'Buyer preview': 'खरीदार पूर्वावलोकन',
      'Materials': 'सामग्री',
      'Made with care': 'सावधानी से बनाया गया',
      'Share Page': 'पेज साझा करें',
      'Product page saved to your Karigar Setu shop.': 'उत्पाद पेज आपके Karigar Setu शॉप में सहेजा गया।',
      'Use another Groq key': 'दूसरी Groq कुंजी उपयोग करें',
      'Create a Product Page': 'उत्पाद पेज बनाएँ',
      'Tap to take a photo': 'फोटो लेने के लिए टैप करें',
      'Listening… tap to stop': 'सुन रहा है… रोकने के लिए टैप करें',
      'Tap and speak naturally — any supported language': 'स्वाभाविक रूप से बोलें — कोई भी समर्थित भाषा',
      'Generate Product Page': 'उत्पाद पेज बनाएँ',
      'Your Groq key is used only for this AI generation request.': 'आपकी Groq कुंजी केवल इस AI अनुरोध के लिए उपयोग होती है।',
      'We could not generate the page': 'पेज नहीं बनाया जा सका',
      'Try again': 'फिर कोशिश करें',
      'Save': 'सहेजें',
      'Share': 'साझा करें',
      'Your Product Page': 'आपका उत्पाद पेज',
      'The story': 'कहानी',
      'Rooted in India': 'भारत की जड़ों से जुड़ा',
      'Made by hand': 'हाथ से बनाया गया',
      'Why it is special': 'यह खास क्यों है',
      'INDIAN CRAFT • HANDMADE': 'भारतीय शिल्प • हस्तनिर्मित',
      'Powered by Karigar Setu • AI-assisted storytelling': 'Karigar Setu द्वारा • AI-सहायित कहानी',
      'Voice input language': 'वॉइस इनपुट भाषा',
      'Speak': 'बोलें',
      'Make your craft discoverable': 'अपनी कला को लोगों तक पहुँचाएँ',
      'No forms. Just show us the product and tell its story in your own voice.': 'फॉर्म नहीं। बस उत्पाद दिखाएँ और अपनी आवाज़ में उसकी कहानी बताएँ।',
      '1. Photograph your product': '1. अपने उत्पाद की फोटो लें',
      '2. Tell its story in your own voice': '2. अपनी आवाज़ में इसकी कहानी बताएँ',
      'Initializing microphone…': 'माइक्रोफ़ोन शुरू हो रहा है…',
      'Gross sales': 'कुल बिक्री',
      'Estimated profit': 'अनुमानित लाभ',
      'Average order': 'औसत ऑर्डर',
      'Sales trend': 'बिक्री का रुझान',
      'Product performance': 'उत्पाद प्रदर्शन',
      'Marketplace comparison': 'बाज़ार तुलना',
      'Your business, at a glance': 'आपके व्यवसाय की एक झलक',
      'Understand what sells, where it sells, and what you earn.': 'क्या बिकता है, कहाँ बिकता है और आप क्या कमाते हैं, समझें।',
      'Your products': 'आपके उत्पाद',
      'Your craft catalog, ready to improve and share.': 'आपकी कला सूची, सुधारने और साझा करने के लिए तैयार।',
      'Search your products': 'अपने उत्पाद खोजें',
      'Prepare each craft on time and keep payment status clear.': 'हर ऑर्डर समय पर तैयार करें और भुगतान की स्थिति स्पष्ट रखें।',
      'Filter orders': 'ऑर्डर फ़िल्टर करें',
      'Update order status': 'ऑर्डर की स्थिति अपडेट करें',
      'Quantity': 'मात्रा',
      'Order total': 'ऑर्डर कुल',
      'Prepare by': 'तैयार करें',
      'Paid': 'भुगतान हो गया',
      'Payment pending': 'भुगतान लंबित',
      'Marketplaces': 'बाज़ार',
      'Choose where you want to offer your craft.': 'चुनें कि आप अपनी कला कहाँ पेश करना चाहते हैं।',
      'Enabled destinations': 'सक्रिय गंतव्य',
      'Groq is the only AI provider used by this build. Your key is kept in app memory for this session.': 'इस बिल्ड में केवल Groq AI का उपयोग होता है। आपकी कुंजी इस सत्र की मेमोरी में रहती है।',
      'Generates the listing in your selected UI language.': 'आपकी चुनी हुई ऐप भाषा में लिस्टिंग बनाता है।',  },
  'mr': {
      'Welcome back': 'पुन्हा स्वागत आहे',
      'Sign in': 'साइन इन',
      'Username': 'वापरकर्ता नाव',
      'Password': 'पासवर्ड',
      'Language': 'भाषा',
      'Your craft. Your story. Your marketplace.': 'तुमची कला. तुमची कथा. तुमची बाजारपेठ.',
      'Sign in to your artisan workspace.': 'तुमच्या कारागीर कार्यक्षेत्रात साइन इन करा.',
      'DEMO ACCESS': 'डेमो प्रवेश',
      'Prototype account only. Replace demo authentication before real deployment.': 'फक्त प्रोटोटाइप खाते. प्रत्यक्ष वापरापूर्वी डेमो प्रमाणीकरण बदला.',
      'Made for the people behind the craft ✦': 'कलेमागील कारागिरांसाठी बनवलेले ✦',
      'Dashboard': 'डॅशबोर्ड',
      'Analytics': 'विश्लेषण',
      'Products': 'उत्पादने',
      'Orders': 'ऑर्डर्स',
      'Marketplace': 'बाजारपेठ',
      'Settings': 'सेटिंग्ज',
      'Home': 'होम',
      'Markets': 'बाजार',
      'Your craft is going places.': 'तुमची कला पुढे जात आहे.',
      'Here’s what’s happening in your artisan business.': 'तुमच्या कारागीर व्यवसायात सध्या काय घडत आहे.',
      'View analytics': 'विश्लेषण पहा',
      'View page': 'पेज पहा',
      'Create a product': 'उत्पादन तयार करा',
      'Create product listing': 'उत्पादन लिस्टिंग तयार करा',
      'Save product': 'उत्पादन जतन करा',
      'Save profile': 'प्रोफाइल जतन करा',
      'Log out': 'लॉग आउट',
      'Groq API key': 'Groq API की',
      'Apply API keys': 'API की लागू करा',
      'AI configuration': 'AI कॉन्फिगरेशन',
      'Artisan profile': 'कारागीर प्रोफाइल',
      'Your name': 'तुमचे नाव',
      'Business / craft name': 'व्यवसाय / कलेचे नाव',
      'Contact number': 'संपर्क क्रमांक',
      'Location': 'स्थान',
      'About your craft / business': 'तुमच्या कला / व्यवसायाबद्दल',
      'Profile saved for this session.': 'प्रोफाइल या सत्रासाठी जतन झाले.',
      'AI keys set in memory for this session.': 'AI की या सत्रासाठी मेमरीमध्ये सेट केल्या.',
      'Take photo': 'फोटो घ्या',
      'Upload photos': 'फोटो अपलोड करा',
      'Craft details': 'कलेचे तपशील',
      'Product name (optional)': 'उत्पादनाचे नाव (पर्यायी)',
      'Category': 'वर्ग',
      'Tell us about the product': 'उत्पादनाबद्दल सांगा',
      'What is it? How is it made? What makes it special?': 'हे काय आहे? हे कसे बनवले जाते? याला खास काय बनवते?',
      'Materials (if known)': 'साहित्य (माहित असल्यास)',
      'Price & production': 'किंमत आणि उत्पादन',
      'Your selling price (₹)': 'तुमची विक्री किंमत (₹)',
      'Units you can make': 'तुम्ही किती युनिट बनवू शकता',
      'In how many days?': 'किती दिवसांत?',
      'AI listing studio': 'AI लिस्टिंग स्टुडिओ',
      'Generate buyer-ready listing': 'खरेदीदारासाठी लिस्टिंग तयार करा',
      'Generating…': 'तयार होत आहे…',
      'Cancel': 'रद्द करा',
      'Close': 'बंद करा',
      'Preview listing': 'लिस्टिंग पहा',
      'Publish (demo)': 'प्रकाशित करा (डेमो)',
      'Demo publish': 'डेमो प्रकाशन',
      'Connect demo': 'डेमो कनेक्ट करा',
      'Share listing': 'लिस्टिंग शेअर करा',
      'Share product page': 'उत्पादन पेज शेअर करा',
      'Buyer preview': 'खरेदीदार पूर्वावलोकन',
      'Materials': 'साहित्य',
      'Made with care': 'काळजीपूर्वक बनवलेले',
      'Share Page': 'पेज शेअर करा',
      'Product page saved to your Karigar Setu shop.': 'उत्पादन पेज तुमच्या Karigar Setu शॉपमध्ये जतन झाले.',
      'Use another Groq key': 'दुसरी Groq की वापरा',
      'Create a Product Page': 'उत्पादन पेज तयार करा',
      'Tap to take a photo': 'फोटो घेण्यासाठी टॅप करा',
      'Listening… tap to stop': 'ऐकत आहे… थांबवण्यासाठी टॅप करा',
      'Tap and speak naturally — any supported language': 'नैसर्गिकपणे बोला — कोणतीही समर्थित भाषा',
      'Generate Product Page': 'उत्पादन पेज तयार करा',
      'Your Groq key is used only for this AI generation request.': 'तुमची Groq की फक्त या AI विनंतीसाठी वापरली जाते.',
      'We could not generate the page': 'पेज तयार करता आले नाही',
      'Try again': 'पुन्हा प्रयत्न करा',
      'Save': 'जतन करा',
      'Share': 'शेअर करा',
      'Your Product Page': 'तुमचे उत्पादन पेज',
      'The story': 'कथा',
      'Rooted in India': 'भारताशी जोडलेले',
      'Made by hand': 'हाताने बनवलेले',
      'Why it is special': 'हे खास का आहे',
      'INDIAN CRAFT • HANDMADE': 'भारतीय कला • हस्तनिर्मित',
      'Powered by Karigar Setu • AI-assisted storytelling': 'Karigar Setu द्वारे • AI-सहाय्यित कथा',
      'Voice input language': 'व्हॉइस इनपुट भाषा',
      'Speak': 'बोला',
      'Make your craft discoverable': 'तुमची कला लोकांपर्यंत पोहोचवा',
      'No forms. Just show us the product and tell its story in your own voice.': 'फॉर्म नाहीत. उत्पादन दाखवा आणि तुमच्या आवाजात त्याची कथा सांगा.',
      '1. Photograph your product': '1. तुमच्या उत्पादनाचा फोटो घ्या',
      '2. Tell its story in your own voice': '2. तुमच्या आवाजात त्याची कथा सांगा',
      'Initializing microphone…': 'मायक्रोफोन सुरू होत आहे…',
      'Gross sales': 'एकूण विक्री',
      'Estimated profit': 'अंदाजे नफा',
      'Average order': 'सरासरी ऑर्डर',
      'Sales trend': 'विक्रीचा कल',
      'Product performance': 'उत्पादन कामगिरी',
      'Marketplace comparison': 'बाजार तुलना',
      'Your business, at a glance': 'तुमच्या व्यवसायाची झलक',
      'Understand what sells, where it sells, and what you earn.': 'काय विकते, कुठे विकते आणि तुम्ही किती कमावता हे समजून घ्या.',
      'Your products': 'तुमची उत्पादने',
      'Your craft catalog, ready to improve and share.': 'तुमची कला सूची, सुधारण्यासाठी आणि शेअर करण्यासाठी तयार.',
      'Search your products': 'तुमची उत्पादने शोधा',
      'Prepare each craft on time and keep payment status clear.': 'प्रत्येक ऑर्डर वेळेत तयार करा आणि पेमेंटची स्थिती स्पष्ट ठेवा.',
      'Filter orders': 'ऑर्डर फिल्टर करा',
      'Update order status': 'ऑर्डरची स्थिती अपडेट करा',
      'Quantity': 'प्रमाण',
      'Order total': 'ऑर्डर एकूण',
      'Prepare by': 'तयार करा',
      'Paid': 'पैसे मिळाले',
      'Payment pending': 'पेमेंट प्रलंबित',
      'Marketplaces': 'बाजारपेठा',
      'Choose where you want to offer your craft.': 'तुमची कला कुठे विकायची ते निवडा.',
      'Enabled destinations': 'सक्रिय ठिकाणे',
      'Groq is the only AI provider used by this build. Your key is kept in app memory for this session.': 'या बिल्डमध्ये फक्त Groq AI वापरले जाते. तुमची की या सत्राच्या मेमरीमध्ये ठेवली जाते.',
      'Generates the listing in your selected UI language.': 'तुमच्या निवडलेल्या अॅप भाषेत लिस्टिंग तयार करते.',  },
}; }
class LText extends StatelessWidget { final String data; final TextStyle? style; final TextAlign? textAlign; final int? maxLines; final TextOverflow? overflow; const LText(this.data,{super.key,this.style,this.textAlign,this.maxLines,this.overflow}); @override Widget build(BuildContext context)=>Text(L10n.t(data),style:style,textAlign:textAlign,maxLines:maxLines,overflow:overflow); }
